insert into product_group (group_name) values ('AccessMidstream');
insert into product_group (group_name) values ('Aera Energy');
insert into product_group (group_name) values ('Alyeska');
insert into product_group (group_name) values ('Apache Corporation');
insert into product_group (group_name) values ('Austrailian Foundation');
insert into product_group (group_name) values ('Chesapeake Energy');
insert into product_group (group_name) values ('Conoco');
insert into product_group (group_name) values ('Denbury Resources');
insert into product_group (group_name) values ('DigitalGlobe Demo');
insert into product_group (group_name) values ('DigitalGlobe Fee');
insert into product_group (group_name) values ('DigitalGlobe Foundation');
insert into product_group (group_name) values ('DigitalGlobe LIDAR');
insert into product_group (group_name) values ('Eagleford Basin');
insert into product_group (group_name) values ('EOG');
insert into product_group (group_name) values ('Exxon Mobil');
insert into product_group (group_name) values ('Exxon Mobil Contractor');
insert into product_group (group_name) values ('Fayetteville Basin');
insert into product_group (group_name) values ('Hilcorp');
insert into product_group (group_name) values ('Kinder Morgan');
insert into product_group (group_name) values ('Noble');
insert into product_group (group_name) values ('NREL');
insert into product_group (group_name) values ('PDO');
insert into product_group (group_name) values ('PDO Source Data');
insert into product_group (group_name) values ('Pioneer Resources');
insert into product_group (group_name) values ('Range Resources');
insert into product_group (group_name) values ('Shell Americas');
insert into product_group (group_name) values ('Shell Canada');
insert into product_group (group_name) values ('Shell Canada UAS');
insert into product_group (group_name) values ('Shell Global');
insert into product_group (group_name) values ('Shell Global Source Data');
insert into product_group (group_name) values ('Shell Iraq');
insert into product_group (group_name) values ('Shell Netherlands');
insert into product_group (group_name) values ('Shell Nigeria');
insert into product_group (group_name) values ('Shell Nigeria ERM');
insert into product_group (group_name) values ('Shell Oman');
insert into product_group (group_name) values ('Shell Qatar');
insert into product_group (group_name) values ('Shell SIEP');
insert into product_group (group_name) values ('Shell TCarta');
insert into product_group (group_name) values ('Shell US');
insert into product_group (group_name) values ('South American Foundation');
insert into product_group (group_name) values ('Southwestern Energy');
insert into product_group (group_name) values ('Statoil');
insert into product_group (group_name) values ('Suncor');
insert into product_group (group_name) values ('Suncor Historical Aerial');
insert into product_group (group_name) values ('Suncor OS Monitoring');
insert into product_group (group_name) values ('Williams Energy');